name: ci
on: { push: { branches: [master] }, pull_request: { branches: [master] } }
permissions: { contents: read }
defaults: { run: { shell: bash } }
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: { matrix: { os: [ubuntu-26.04, macos-15, windows-2025-vs2026] }, fail-fast: false }
    steps: [uses: actions/checkout@v7, uses: kjanat/runner@master, run: run -s make test]
